### ISSUE TITLE
Komen

### ISSUE THREAD

**Issue by ncopz** [nugrohoff/web_sekolah#1]
Sayang ga bisa komen di artikelnya dan fitur ckeditornya minim sekali jadi kalo untuk sekolahan masih kurang buat edit artikelnya, salah satunya untuk mengupload gambar ga bisa di resize atau ditambahkan/diselipkan di paragraf berikutnya.

**Comment by ri8q9** [comment]
apanya?

Pada tanggal Min, 17 Jan 2021 02.11, kickers <notifications@github.com>
menulis:

**Comment by nugrohoff** [comment]
> Sayang ga bisa komen di artikelnya dan fitur ckeditornya minim sekali jadi kalo untuk sekolahan masih kurang buat edit artikelnya, salah satunya untuk mengupload gambar ga bisa di resize atau ditambahkan/diselipkan di paragraf berikutnya.

namanya juga free, kalo mau fiturnya lengkap ya cari yg berbayar

**Comment by ncopz** [comment]
> > Sayang ga bisa komen di artikelnya dan fitur ckeditornya minim sekali jadi kalo untuk sekolahan masih kurang buat edit artikelnya, salah satunya untuk mengupload gambar ga bisa di resize atau ditambahkan/diselipkan di paragraf berikutnya.
> 
> namanya juga free, kalo mau fiturnya lengkap ya cari yg berbayar

wkwkwkkwkw parah.. indo banget jawabnya. ok trims deh
